version: '3.7'

services:
  # Bot container
  bot:
    container_name: bot
    build:
      context: .
      dockerfile: dockerfiles/DockerfileBot
    networks:
      - default
    environment:
      - lhost=lavalink
      - lport=2333
      - lpass=TTT
    command: python main.py
    volumes:
      - .:/usr/src/app
  api:
    container_name: api
    build:
      context: .
      dockerfile: dockerfiles/DockerfileBot
    ports:
      - "5000:5000"
    networks:
      - default
    command: python main.py api
    volumes:
      - .:/usr/src/app

  # All other container
  redis:
    image: "redis:alpine"
    command: redis-server --requirepass SoMsEcUrEpassword
    environment:
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - "6000:6379"
    networks:
      - default
    volumes:
      - 'redis_data:/bitnami/redis/data'

  celery:
    container_name: celery
    build:
      context: .
      dockerfile: dockerfiles/DockerfileCelery
    depends_on:
      - redis
    networks:
      - default
    command: celery -A base_folder.celery.worker worker --loglevel=info
    volumes:
      - .:/usr/src/app

  lavalink:
    container_name: lavalink
    build:
      context: .
      dockerfile: dockerfiles/DockerfileLavalink
    ports:
      - "2333:2333"
    command: lavalink

volumes:
  redis_data:
    driver: local

networks:
  default:
    external:
      name: bot-network