version: '3.7'

services:

  m3e5:
    container_name: m3e5
    build:
      context: .
      dockerfile: dockerfiles/DockerfileBot
    command: python main.py
    volumes:
      - .:/usr/src/app

  redis:
    image: "redis:alpine"
    command: redis-server --requirepass SoMsEcUrEpassword
    environment:
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - "0.0.0.0:5672:5672"
    volumes:
      - 'redis_data:/bitnami/redis/data'

  celery:
    container_name: celery
    build:
      context: .
      dockerfile: dockerfiles/DockerfileCelery
    depends_on:
      - redis
    command: celery -A base_folder.celery.worker worker --loglevel=info
    volumes:
      - .:/usr/src/app

volumes:
  redis_data:
    driver: local